[package]
name = "scribble"
version = "0.2.0"
edition = "2024"

[dependencies]
eframe = "0.28"
egui = "0.28"
regex = "1.0"
arboard = "3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.14"
image = "0.25"
